general:
  config: "leNet_5"       # [ leNet_1 - leNet_4 - leNet_5 ]
  device: "cpu" # cpu or cuda
  dataset:
    name: "usps" # [ usps for leNet_1 and leNet_4, mnist for leNet_5]
    filename: "E:\\CNN Models\\dataset\\usps\\usps.h5"
    ImageSize: 32
    num_classes: 10

train:
  seed: 192
  epochs: 50
  lr: 0.0001
  num_workers: 0
  batch_size: 10
  test_batch_size: 10
  cuda: false
  mixed_precision: "no" # "no" # "fp16" # "bf16"
  save_every: 1

test:
  batch_size: 10
  checkpoint: ""
  output_dir: ""
  epoch: 1
  num_workers: 0
  cuda: false 
